package Model;
// Generated 30 janv. 2024 10:33:01 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Identifications generated by hbm2java
 */
@Entity
@Table(name="identifications"
    ,catalog="empreinte"
)
public class Identifications extends BaseModel implements java.io.Serializable {



     private Date date;
     private Date heureDebut;
     private Date heureFin;
     private String heureTotal;
     private Integer idInscription;
     private String nom;
    public Identifications() {
    }

    public Identifications(Date date, Date heureDebut, Date heureFin, String heureTotal, Integer idInscription,String nom) {
       this.date = date;
       this.heureDebut = heureDebut;
       this.heureFin = heureFin;
       this.heureTotal = heureTotal;
       this.idInscription = idInscription;
       this.nom=nom;
    }
   

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="heureDebut", length=19)
    public Date getHeureDebut() {
        return this.heureDebut;
    }
    
    public void setHeureDebut(Date heureDebut) {
        this.heureDebut = heureDebut;
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="heureFin", length=19)
    public Date getHeureFin() {
        return this.heureFin;
    }
    
    public void setHeureFin(Date heureFin) {
        this.heureFin = heureFin;
    }

    
    @Column(name="heureTotal")
    public String getHeureTotal() {
        return this.heureTotal;
    }
    
    public void setHeureTotal(String heureTotal) {
        this.heureTotal = heureTotal;
    }

    
    @Column(name="idInscription")
    public Integer getIdInscription() {
        return this.idInscription;
    }
    
    public void setIdInscription(Integer idInscription) {
        this.idInscription = idInscription;
    }




}


